+ 测试人员：明鑫
+ 测试时间：2019.09.07 21:24
+ 测试平台：个人笔记本电脑windows10, python3.6, mysql 8.0.17
+ 接口url: /authen/authenticateByPhoneNumber,/authen/finishAuthenticateByPhoneNumber
+ 测试版本：branchName = demo; commitID = 88acdb04f70a9cd18ebc242e7e8489a3b2e3b1c6
### 测试内容
测试个人实名认证。为了测试，我们实现在后端数据库中准备了一些个人用户数据：
```
user1 = IndividualUser.IndividualUser(
    nickname='Lucy', password='123', sex='female',
    name='Lucy', birth='1996.01.01', residence_address='Nanjing University',
    education='bachelor', school='NJU', work_address='NJU',
    live_address='NJU', marriage='married', salary='3000',
    vehicle_property='300000', house_property='0', vehicle_loan='0', house_loan='0',
    work_year='3', job='whiteCollar'
)
user2 = IndividualUser.IndividualUser(
    nickname='Mike', password='123', sex='male',
    name='Mike', birth='1996.02.01', residence_address='Nanjing University',
    education='bachelor', school='NJU', work_address='NJU',
    live_address='NJU', marriage='married', salary='3000',
    vehicle_property='300000', house_property='0', vehicle_loan='0', house_loan='0',
    work_year='3', job='whiteCollar'
)
```
#### 测试样例1
先发送给/authen/authenticateByPhoneNumber
```python
userid:2
name:%E9%A2%9C%E7%95%AA(颜番)
id_card:513029199608195472
number:15951958919
```
response为：
```
{
    "content": null,
    "message": "比对成功！验证码已经发送！",
    "success": true
}
```
接着短信验证码发送，短信验证为116606。

接着发送给/authen/finishAuthenticateByPhoneNumber

```python
userid:2
name:%E9%A2%9C%E7%95%AA(颜番)
id_card:513029199608195472
number:15951958919
code:116606
```

response为：

```
{
    "content": null,
    "message": "实名认证成功！",
    "success": true
}
```

接着查看数据库，userid为2的用户实名认证信息已经更新成功。

接着再发送同样的信息给/authen/finishAuthenticateByPhoneNumber

```python
userid:2
name:%E9%A2%9C%E7%95%AA(颜番)
id_card:513029199608195472
number:15951958919
code:116606
```

response为：

```
{
    "content": null,
    "message": "请检查验证码是否输入正确！",
    "success": false
}
```

这是因为验证码成功使用过一次后就被销毁，因此再发送同样的验证码会失败。

#### 测试样例2
先发送给/authen/authenticateByPhoneNumber

```python
userid:2
name:%E9%A2%9C%E7%95%AA(颜番)
id_card:513029199608195472
number:10000000000
```

response为：

```
{
    "content": null,
    "message": "比对失败！请检查输入！",
    "success": false
}
```

输入信息有误，返回失败信息，不发送验证码。

#### 测试样例3
先发送给/authen/authenticateByPhoneNumber

```python
userid:2
name:%E9%A2%9C%E7%95%AA(颜番)
id_card:513029199608195472
number:15951958919
```

response为：

```
{
    "content": null,
    "message": "比对成功！验证码已经发送！",
    "success": true
}
```

接着短信验证码发送，短信验证为452211。

接着发送给/authen/finishAuthenticateByPhoneNumber

```python
userid:2
name:%E9%A2%9C%E7%95%AA(颜番)
id_card:513029199608195472
number:15951958919
code:111111
```

response为：

```
{
    "content": null,
    "message": "请检查验证码是否输入正确！",
    "success": false
}
```

验证码输入错误，返回错误信息。

200s后，发送给/authen/finishAuthenticateByPhoneNumber

```python
userid:2
name:%E9%A2%9C%E7%95%AA(颜番)
id_card:513029199608195472
number:15951958919
code:452211
```

response为：

```
{
    "content": null,
    "message": "请检查验证码是否输入正确！",
    "success": false
}
```

此时验证码已经过期（有效期3分钟），因此输入了刚才发送的验证码已经无效。符合测试预期。

## 测试发现的问题及改进
暂无
